path: C:\Users\EXCALIBUR\Desktop\pasive_project\BrainTumorsDetection

train: images/train # relative to path
val: images/val # relative to path
test: images/test # relative to path

# Class Names
names: ["Tumor"]
